eureka:
  client:
    service-url:
      defaultZone: http://localhost:8051/eureka/  
  instance:
    prefer-ip-address: true 
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}


server:
  port: 9998
  
spring:
  application:
    name: shop-config-server
        
      
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
    
spring.cloud.config.server.git.uri: https://github.com/www-DeMarcia-com/shop-config.git   