eureka:
  client:
    service-url:
      defaultZone: http://localhost:8051/eureka/  
  instance:
    prefer-ip-address: true 
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}


server:
  port: 9999
  
spring:
  application:
    name: shop-zuul
  redis:
    port: 6379
    password: 
    host: localhost
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8


    
zuul:
  routes:
    shop-index-web: /shop-index-web/**
    #不加这句话导致session不一致
    intelligentsia-authority: 
      sensitive-headers: Authorization
      
      
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
    

#zuul.routes.intelligentsia-authority.sensitiveHeaders: Authorization   
    