eureka:
  client:
    service-url:
      defaultZone: http://localhost:8051/eureka/  
  instance:
    prefer-ip-address: true 
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}


server:
  port: 8061
  
  
spring:
  application:
    name: shop-redis-service